#!/bin/bash
# install new vim packages from github and add them as a submodule 
#  or just clone them to test out

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH

containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

if [ -z "$1" ]; then
    echo "usage: $0 [-t] bundle|colors https://github.com/<user>/<repo>.git"
    echo "   example: addvimpackage -t colors https://github.com/jnurmine/Zenburn.git"
    exit 1
fi

valid=("-t" "bundle" "colors")
if ! containsElement "$1" "${valid[@]}"; then
    echo only valid: "${valid[@]}"
    exit 1
fi

if [ $1 = "-t" ]; then
    dir=$2
    url=$3
    set -x
    mkdir -p  ~/.vim/$dir
    cd ~/.vim/$dir
    echo git clone $url

else
    dir=$1
    url=$2
    package=$(echo $url | awk -F / '{print $NF}' | cut -d '.' -f 1)
    set -x
    mkdir vim/$dir
    echo git submodule add $url vim/$dir/$package
fi

cd $SCRIPTPATH

if [[ $dir = "colors" ]]; then
    #color files need to be in .vim/colors/colorfile.vim
    for f in $(find vim/$dir/$package -name '*.vim' ); do
        ln -s $f vim/$dir/
    done
fi
