#!/bin/bash
#install dotfiles

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
olddir=~/dotfiles_old
exclude="install|README.md|LICENSE"

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $(ls $SCRIPTPATH | egrep -vi $exclude); do
    #[ -d $file ] && continue
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/ 2>/dev/null
    echo "Creating symlink to $file in home directory."
    ln -s $SCRIPTPATH/$file ~/.$file
done
