#!/bin/bash
#install dotfiles

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
olddir=~/dotfiles_old
# just in case we run install twice
if [ -d $olddir ]; then
    olddir=${olddir}_$$
fi
exclude="install|README.md|LICENSE"

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $(ls $SCRIPTPATH | egrep -vi $exclude); do
    mv -f ~/.$file $olddir/ 2>/dev/null
    echo ln -fs $SCRIPTPATH/$file ~/.$file
    ln -fs $SCRIPTPATH/$file ~/.$file || echo "failed ln -s $SCRIPTPATH/$file ~/.$file"
done

#cd ~/.vim/bundle/YouCompleteMe
#./install.py --clang-completer
#
##Error I fixed on fedora
#libtinfo=$(ls /lib64/libtinfo.so*)
#if [ "$libtinfo" = "" ]; then
#    echo /lib*/libtinfo.so missing!!! run ldd on ycm_core.so if ycm fails
#    echo and link libncurses to it to fix it
#    #cd /lib64
#    #sudo ln -s libncurses.so.* libtinfo.so.*
#fi

#adittional things needed:

##fedora
#sudo yum install pylint flake8 autopep8

#mac
# install hombrew
# brew install cmake
# brew install flake8
# brew install autopep8
# brew install python3
# brew install pip
# brew install wget
# wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
# pip install pylint


##for YoucompleteMe follow guide in - https://github.com/Valloric/YouCompleteMe
