#!/bin/bash
#install dotfiles

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
olddir=~/dotfiles_old
exclude="install|README.md|LICENSE"

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $(ls $SCRIPTPATH | egrep -vi $exclude); do
    #[ -d $file ] && continue
    mv -f ~/.$file ~/dotfiles_old/ 2>/dev/null
    echo ln -fs $SCRIPTPATH/$file ~/.$file
    ln -fs $SCRIPTPATH/$file ~/.$file || echo "failed ln -s $SCRIPTPATH/$file ~/.$file"
done

#for YoucompleteMe - https://github.com/Valloric/YouCompleteMe
#steps for Fedora!
sudo dnf install automake gcc gcc-c++ kernel-devel cmake
sudo dnf install python-devel python3-devel
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer

#Error I fixed on fedora
libtinfo=$(ls /lib64/libtinfo.so*)
if [ "$libtinfo" = "" ]; then
    echo /lib*/libtinfo.so missing!!! run ldd on ycm_core.so if ycm fails
    echo and link libncurses to it to fix it
    #cd /lib64
    #sudo ln -s libncurses.so.* libtinfo.so.*
fi

#for syntastic
#fedora
sudo yum install pylint
#TODO install c, c++ checkers
